# Generated by Django 4.0.6 on 2022-10-27 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OurClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('class_tel', models.CharField(max_length=20)),
                ('class_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('user', 'user'), ('school', 'school'), ('admin', 'admin'), ('not-active', 'not-active')], default='user', max_length=24)),
                ('card_id', models.CharField(max_length=100, null=True)),
                ('fullname', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('telephone', models.CharField(max_length=20)),
                ('balance', models.FloatField(default=0)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexapp.ourclass')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=40)),
                ('school_tel', models.CharField(max_length=20)),
                ('school_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ourclass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexapp.school'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrive_time', models.DateTimeField(auto_now=True)),
                ('alcohol_level', models.FloatField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexapp.student')),
            ],
        ),
    ]
