# Generated by Django 4.0.6 on 2022-10-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='card_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
