# Generated by Django 4.0.6 on 2022-10-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0002_alter_student_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='success',
            field=models.IntegerField(default=0),
        ),
    ]
