# Generated by Django 4.0.6 on 2022-10-31 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0003_alter_attendance_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='success',
        ),
    ]
