# Generated by Django 4.0.6 on 2022-10-31 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0005_attendance_class_attend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourclass',
            old_name='device',
            new_name='identifier',
        ),
    ]
