# Generated by Django 4.0.6 on 2022-10-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0006_rename_device_ourclass_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourclass',
            name='identifier',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
