# Generated by Django 4.0.6 on 2022-11-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0007_alter_ourclass_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
